chanzuckerberg/sci-components

.storybook/preview.js, package.json, src/core/Tabs/index.stories.tsx, src/core/Tabs/index.tsx, src/index.ts, yarn.lock
This isn't feature complete but definitely demoable.
A Major change is removing the automatic action creation based on regex match.  This was removing any controlled functionality connected to event handling.
Adds @emotion/css import to allow exporting a css definition as a class name
=> feat(component): Create Tabs

src/core/MenuItem/index.stories.tsx, src/index.ts
Add more examples and fix styling bug
If MUI `<Menu />` is missing `label` prop, the style outline will overlap the label:
BAD:
`<Menu ... />`
GOOD:
`<Menu label="Name" ... />`
=> thuang-fix-multiselect

src/core/Tooltip/index.stories.tsx, src/core/Tooltip/index.tsx, src/core/Tooltip/style.ts, src/index.ts
Adds `Tooltip`, with inverted options. White (info) by default, black for action tooltip.
~~**Design Link:** https://chanzuckerberg.invisionapp.com/console/share/UWVLU4OH37F/511021232/play~~
**Design Link (updated):** https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=642%3A4116
Default white info tooltip:
Inverted black action tooltip:
=> Add Tooltip

.eslintrc.js, package.json, src/core/Chip/index.stories.tsx, src/core/Chip/index.tsx, src/core/Chip/style.ts, src/core/Tooltip/index.stories.tsx, src/core/styles/common/mixins/fonts.ts, src/index.ts
1. Add chip (or tag as called in our design system)
2. Export `fontCaps` mixins
3. Add Tooltip styling arrow example
=> add Chips and export fontCaps mixins

package.json, src/core/Tooltip/index.stories.tsx, src/core/Tooltip/index.tsx, src/core/TooltipTableContent/index.stories.tsx, src/core/TooltipTableContent/index.tsx, src/core/TooltipTableContent/style.ts, src/core/styles/common/mixins/fonts.ts, src/index.ts
Adds the TooltipTableContent component and shows an example of how to pass it in to the Tooltip component.
I decided to make the content its own component since in IDseq, we have this tooltip follow the user's cursor. (The table is passed in to `ReactDOM.createPortal()`
I also added the option to include a short message/alert and to disable sections of the table contents. We use this in IDseq in the heatmap:
**Example from current IDseq**
**Design link:** https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=642%3A4116
**Base `TooltipTableContent` example:**
**`TooltipTable` example:**
=> Add TooltipTable (content) and stories

package.json, src/core/Button/index.stories.tsx, src/core/Button/index.tsx
This PR is needed to work with our Tooltip component per https://material-ui.com/components/tooltips/#custom-child-element. Essentially if we supply a child element to Tooltip that's NOT MUI component, we'll need to forward ref 💡 😄 👌 !
PTAL thank you!
=> Thuang add ref to button

src/common/types/svg.d.ts, src/core/Checkbox/index.tsx
In svgr, the react component is not the default export.  Assuming the default incorrectly was causing storybook not to load.  Now the type definition is accurate and imports need to use `import {ReactComponent as SomeSvgName}...`
=> Fix svg type declaration.

package.json, rollup.config.js, yarn.lock
This PR adds `@rollup/plugin-url` to mirror our Storybook webpack setup, which uses (svgr and url loader), otherwise `yarn build` will break, because `@rollup/svgr` by default exports the `ReactComponent`, but adding the url loader will set change `ReactComponent` as named export. 
E.g.,
```ts
// Default Import -- without url loader, default export is ReactComponent
import IconCheckboxChecked  from "../../common/svgs/IconCheckboxChecked.svg";
// Named Import -- with url loader, default is the blob url
import { ReactComponent as IconCheckboxChecked } from "../../common/svgs/IconCheckboxChecked.svg";
```
And since before this PR, Webpack uses both svgr and url loader already, storybook wants Named Import, but `yarn build` runs Rollup, which didn't have url loader, so it still wanted Default …
=> thuang-fix-rollup-svgr

src/core/Checkbox/index.tsx, src/core/Checkbox/styles.ts, src/core/styles/common/defaultTheme.ts
[ticket link](https://app.clubhouse.io/sci-design-system/story/160102/hotfix-align-label-for-svg-inputs)
See comment [here](https://github.com/chanzuckerberg/sci-components/pull/52#discussion_r703744174). The misalignment on the radio button is also seen on the checkbox icons. 
This ticket adds an input object to the icon size object in the default theme and adds new css rules to ensure the correct size is used for the icon
**Because the checkbox is already implemented, this change could cause shifts in layout once it's released.**
=> hotfix checkbox alignment

.husky/prepare-commit-msg, docs/contribution.md, package.json, yarn.lock
This PR follows Commitizen's [documentation](https://github.com/commitizen/cz-cli#husky) to install and add prepare commit message hook to trigger Commitizen command and also added a README section!
From now on when we add a new commit, Commitizen will walk you through a set of questions to properly prepare the right commit message that follows Semantic Versioning 🙆‍♂️ 
NOTE: If you just want to make a quick commit, you can `^ + C` to escape Commitizen and use your existing commit message too!
=> chore: add Commitizen

src/core/InputDropdown/index.stories.tsx, src/core/InputDropdown/styles.ts
- **What:** Fix styles for inputdropdown when menu is open
- **Why:** I missed that there was a separate state for this when implementing
- **Env:** http://localhost:6006/?path=/story/inputdropdown--minimal
=> tweak styles for minimal input dropdown when open

src/core/Menu/index.stories.tsx, src/core/Menu/index.tsx
- **What:** Customize the placement of the czifui `Menu`, relative to its anchor element
- **Why:** Depending on where the anchor is on the screen, the default may not be desirable
- **Env:** http://localhost:6006/?path=/story/menu--custom-placement
=> allow menu consumers to customize menu placement when necessary

src/core/Button/index.stories.tsx, src/core/Button/index.tsx, src/core/Button/style.ts, src/core/ComplexFilter/index.tsx
- Style updates to existing buttons.  
- Implements sdsType and sdsStyle as optional props
- Adds more stories to storybook
This is backward compatible, but we should clean up at some point once teams update.
Default state:
Hover state:
(Couldn't screenshot the click state, but it's there)
Different states in Storybook:
=> Button updates

README.md, src/core/ComplexFilter/style.ts
**Documentation**
Shortcut ticket: [sh-164653](https://app.shortcut.com/sci-design-system/story/164653/spike-test-styling-an-sds-component-with-css-modules-in-a-sandbox-environment)
Update docs to reflect how default theme is implemented in a project (add emotion theme wrapper)
Also add z-index to ComplexFilter dropdown to allow it to be rendered in a portal as IDseq will be doing
N/A
~- [ ] Default Story~
~- [ ] LivePreview Story~
~- [ ] Test Story~
~- [ ] Tests written~
~- [ ] Variables from `defaultTheme.ts` used wherever possible~
~- [ ] If updating an existing component, depreciate flag has been used where necessary~
=> docs(readme): update setup docs to reflect how to use default theme

src/core/MenuSelect/index.tsx
This PR adds an `onInputChange` prop of type `(event: React.SyntheticEvent) => void` that is passed to the `onChange` prop of the child `StyledInputBase` component. This allows anyone using the `MenuSelect` component to pass a callback function that fires whenever a user changes input in the search box.
This functionality is needed by Aspen - we want a dropdown list of locations, but there are >20,000 possibilities. We need this functionality to limit what options are passed to the component based on what the user is searching for.
=> feat(menuselect): add onInputChange prop to MenuSelect

src/core/ComplexFilter/index.tsx, src/core/MenuSelect/style.ts
I think the reason why `pendingValue` is `[]` is because I added `<ClickAwayListener />` component, following MUIv5's example [here](https://mui.com/components/autocomplete/#githubs-picker), which also has the same problem 😆 
The problem is:
1. Click on click target to open menu dropdown
2. Select an option (value: [], pendingValue: [1])
3. Click on click target, `handleClick()` will `setPendingValue(value)` (value: [], pendingValue: []) <--- pendingValue is back to `[]`
4. Now `ClickAwayListener` detects we're clicking outside of the container it's watching, so it fires `handleClose()`, which then `setValue(pendingValue)` (value: [], pendingValue[]) <-- both value and pendingValue are back to `[]`
So the solution in this PR is to remove `setPendingValue(value)` from `handleClick()`, …
=> fix(complexfilter): click target preserves pending value

src/core/Icon/index.stories.tsx, src/core/Icon/index.tsx, src/core/Icon/map.ts, src/core/Icon/style.ts
Add type hinting that given a props.iconName, props.sdsSize is narrowed down to values available to
the props.iconName
Example:
`barChartHorizontal3` only accepts `"xs" | "s"`, so passing `sdsSize="l"` throws a TS error 🙆‍♂️ 
[Slack context](https://czi-sci.slack.com/archives/C01TD8YUE86/p1636156524002000)
=> refactor(icon): refactor icon component to add type hinting

src/core/IconButton/index.tsx
Since functional components don't have `ref` prop, we need to use `forwardRef` to pass `props.ref` to the target component manually!
Thanks again for spotting this, @codemonkey800 🙏 
Context: https://docs.google.com/document/d/1p7y8qptmw4rrURSEjV7ApAqAzBNMIhQKjn7Obz69dJo/edit#bookmark=id.kx5wxx9qmisj
=> fix(iconbutton): iconButton now forwards ref

README.md
---
title: "type_of_change(scope_of_work): ticket title"
reviewers: "sds-eng, sds-design"
---
The repo's readme has two images with some alt text. I'm proposing some more descriptive alt text because I like to contribute alt text for fun! 
Fixes #107
Shortcut ticket: none
^I don't think any of this checklist applies to this change, but please let me know if there is something I should account for.
I know reviewing alt text isn't something everyone has experience with, so if you'd like to know my thought process I'd be happy to discuss and link resources on this PR. Thanks in advance for reviewing my work! 🌻
=> fix: Update README alt text

src/core/MenuSelect/index.stories.tsx, src/core/MenuSelect/index.tsx
Expose InputBaseProps as an API
fix #121
---
title: feat(menuselect): add InputBaseProps
reviewers: sds-eng
---
https://github.com/chanzuckerberg/sci-components/issues/121
As seen below, we can now pass props (e.g., placeholder) to `InputBase` as expected!
=> feat(menuselect): add InputBaseProps

src/core/Dialog/index.tsx, src/core/DialogActions/index.tsx, src/core/DialogPaper/index.tsx, src/core/DialogTitle/components/CloseButton/index.tsx, src/core/DialogTitle/index.tsx, src/core/Icon/index.tsx, src/core/Link/index.tsx, src/core/Tooltip/index.tsx, src/core/Tooltip/style.ts
When we do `export default forwardRef(function Component(...))` the generated type definitions
confuse TS, since all the components exported that way share the same _default namespace, thus the
need to do: `const ComponentName = forwardRef(function ComponentName(...)); export default
ComponentName`
=> fix: some components are exported anonymously, which confuses TS somehow

src/core/Link/style.ts
It seems like somehow `import { LinkProps as Props }` confuses TS, so changing it to  `import { LinkProps as RawLinkProps }` to unblock Single Cell! Thank you!
=> fix(link): fix LinkProps export

src/core/Dropdown/index.tsx
- **What:** Allow Dropdown component to accept various Popper and Paper rendering functions, rather than only accepting a StyledComponent
- **Why:** 
- To simplify the process of customizing a Dropdown
- to bring these types in line with the other customizable prop, `InputComponent`
- enables https://github.com/chanzuckerberg/czgenepi/pull/982/files
No visual changes.
=> fix(dropdown): allow custom renderer for Dropdown popper and paper

src/core/Tabs/__snapshots__/index.test.tsx.snap, src/core/Tabs/components/LabelWithCount/index.tsx, src/core/Tabs/components/LabelWithCount/style.ts, src/core/Tabs/components/common.ts, src/core/Tabs/index.stories.tsx, src/core/Tabs/index.test.tsx, src/core/Tabs/index.tsx, src/core/Tabs/style.tsx
**Structural Element (Gene)**
Shortcut ticket: [161558](https://app.shortcut.com/sci-design-system/story/161558/complete-tabs-component)
Copy ticket description here:
**Add Small variant to Tabs component:**
1. Label font should be `fontBodyXs`
2. Label font weight should be `fontWeightSemibold`
**Prop to remove persistent underline:**
1. Add prop option to enable or disable persistent underline from Tabs component (both Large and Small variants)
**Add counter to Large variant:**
1. Add prop option to add a Counter to Tabs component
2. For `Large` variant, counter should be `fontBodyXs`
3. For `Large` variant, there should be `spaceL` between Label and Counter
4. Counter should be color `gray500`
5. Counter should be center aligned to Label
**Add counter to Small variant:**
1. Add prop …
=> feat(tabs): Add count and small variant

src/core/InputDropdown/__snapshots__/index.test.tsx.snap, src/core/InputDropdown/style.ts, src/core/MenuItem/index.stories.tsx, src/core/MenuItem/index.tsx, src/core/MenuItem/style.ts
- **What:** Add disabled MenuItem styles
- **Ticket:** [[sc-168693]](https://app.shortcut.com/genepi/story/168693)
=> feat(menuitem): add disabled menuitem styles

src/core/Tooltip/__snapshots__/tooltip.test.tsx.snap, src/core/Tooltip/index.stories.tsx, src/core/Tooltip/index.tsx, src/core/Tooltip/tooltip.test.tsx
**Structural Element (Genes)**
Shortcut ticket: [sh-176947](https://app.shortcut.com/sci-design-system/story/176947)
Don't render a tooltip that has no title or subtitle because an empty tooltip is awkward and doesn't align with MUI default behavior.
=> fix(tooltip): don't render tooltip that doesn't have content

src/core/ButtonDropdown/index.stories.tsx, src/core/ButtonDropdown/index.tsx, src/core/Dialog/__snapshots__/index.test.tsx.snap, src/core/Icon/style.ts, src/core/InputDropdown/__snapshots__/index.test.tsx.snap, src/core/Notification/__snapshots__/notification.test.tsx.snap, src/index.ts
Shortcut ticket: [sh-157948](https://app.shortcut.com/sci-design-system/story/157948/implement-buttondropdown)
**Acceptance Criteria:**
* `ButtonDropdown` is added to code repo and viewable in Storybook
* Has both rounded and square `sdsStyle` props
* Has primary and secondary `sdsType` props
* Has the same states as other Button components
**Designs:**
https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=1876%3A21349
=> feat(buttondropdown): implement ButtonDropdown component

src/common/styles-dictionary/css/variables.css, src/common/styles-dictionary/scss/_variables.scss, src/common/styles-dictionary/style-dictionary.json, src/core/Link/index.stories.tsx, src/core/Link/style.ts, src/core/styles/common/defaultTheme.ts
**Structural Element (Gene)**
Shortcut ticket: [sh-154874](https://app.shortcut.com/sci-design-system/story/154874/implement-dashed-link-component)
- Add link border style variables to the repo and storybook
- borderLinkDashed
- borderLinkSolid
- Add sdsStyle: Dashed to the Link component
- Dashed Link has states for default, hover, and click
- follow specs in Ref doc
- Dashed Link and bottom border both inherit color from parent text color
- ~~[ ] Test Story in Storybook~~
- ~~[ ] Tests written~~
=> feat(link): add dashed styles and prop, update defaultTheme and styles-dictionary

src/core/TooltipCondensed/index.stories.tsx, src/core/TooltipCondensed/index.test.tsx, src/core/TooltipCondensed/index.tsx, src/core/TooltipCondensed/style.ts, src/index.ts
**Structural Element (Gene)**
Shortcut ticket: [sh-152183](https://app.shortcut.com/sci-design-system/story/152183/implement-tooltipcondensed-component-for-sds)
**Props**
- `indicator`: true | false;
- `indicatorColor`: string
=> feat(tooltipcondensed): add component, stories and tests

src/common/styles-dictionary/css/variables.css, src/common/styles-dictionary/scss/_variables.scss, src/common/styles-dictionary/style-dictionary.json
Adds new overlay colors and removes old ones.
BREAKING CHANGE: Old overlay colors are removed, so any users will no longer have access to them.
**Structural Element (Base)**
Shortcut ticket: [sh-161335](https://app.shortcut.com/sci-design-system/story/161335/implement-overlay-colors)
Adding overlay color values enables greater flexibility in future components by simplifying overlay coloring effects to a single universal color variable.
=> feat: adds new overlay colors

src/core/MenuSelect/index.tsx
onInputChange API actually collapses with MUI Autocomplete's onInputChange, so let's remove it
BREAKING CHANGE: Removes onInputChange API. A code search shows that no product uses this API
anymore
=> fix(menuselect): remove onInputChange API

src/core/MenuItem/index.stories.tsx, src/core/MenuItem/style.ts
* Updated the class names related to "MuiListItem"
* No change for prop "listItemClasses" -> "classes"since we didn't use it
* Updated the stories for MenuItem to remove the `makeStyles` import
* The margins for `FormControl` were changed from 40px -> 38px
* Updated the `FormControl` components in the stories to specify the variants (the default variant changed from `standard` to `outlined` in v5)
=> refactor(menuitem): update MenuItem classNames and stories

src/core/Alert/style.ts, src/core/Callout/style.ts, src/core/Notification/__snapshots__/notification.test.tsx.snap, src/core/Notification/style.ts
We need to explicitly set the background colors now.
The colors defined in our theme seem to be slightly different from what the background color of Alert previously defaulted to, so this should be reviewed by a designer to determine what color we actually want to use. I set them all to 100 for now.
=> style(alert): fix colors on alerts

src/core/ComplexFilter/style.ts, src/core/InputSearch/__snapshots__/index.test.tsx.snap, src/core/InputSearch/style.ts, src/core/MenuItem/style.ts, src/core/MenuSelect/index.tsx, src/core/MenuSelect/style.ts
This change touches `ComplexFilter`, `MenuSelect`, `InputSearch`, and `MenuItem`, since `ComplexFilter` uses all of them!
TODO: I haven't had a chance to fix `MenuSelect` and `Dropdown` yet, but they are both super similar to `ComplexFilter`, so the same fix should work there too!
=> fix(complexfilter): Update ComplexFilter

src/common/styles-dictionary/style-dictionary.json, src/core/InputToggle/__snapshots__/index.test.tsx.snap, src/core/InputToggle/index.stories.tsx, src/core/InputToggle/index.test.tsx, src/core/InputToggle/index.tsx, src/core/InputToggle/style.ts, src/core/styles/common/defaultTheme.ts
- **What:** Add `InputToggle` component
- **Ticket:** [[sc-157940]](https://app.shortcut.com/sci-design-system/story/157940)
- **Design:** https://www.figma.com/proto/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=1876%3A21139&scaling=min-zoom&page-id=642%3A1
=> feat(inputtoggle): add an inputtoggle

src/core/Alert/style.ts, src/core/Callout/style.ts, src/core/Notification/__snapshots__/notification.test.tsx.snap, src/core/Notification/style.ts
- **What:** set appropriate bg color for alert, callout, notification, rather than using the mui default colors
- **Why:** To match design spec
- **Design:** https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=5683%3A87200
The visual change is very subtle, but more noticeable in callouts that have zebra tables. I only noticed this because I was trying to make a table in a callout in czge and the colors were wonky looking.
=> fix(alert, callout, notification): set appropriate bg color

src/core/styles/common/defaultTheme.ts
https://app.shortcut.com/sci-design-system/story/194499/update-defaulttheme-ts-to-avoid-using-defaultthemecolors
=> fix: allow consuming apps to override colors in borders

src/core/Tooltip/__snapshots__/tooltip.test.tsx.snap, src/core/Tooltip/index.stories.tsx, src/core/Tooltip/index.tsx, src/core/Tooltip/tooltip.test.tsx
- **What:** Even when we don't show a tooltip, still render the children
- **Why:** Oops! Otherwise even the components that are wrapped up by the tooltip won't be rendered
=> fix(tooltip): even when we don't render tooltip, show children

src/core/Callout/index.tsx
- **What:** Allow a consumer to conditionally assign a custom icon to callout
- **Why:** I have a component that is based on Callout, which wants to provide a custom icon _sometimes_. As is, if the component passes `icon={iconComponent}`, it works, but then if `iconComponent` is undefined, sds Callout reverts to using the mui default icon because `icon={undefined}` gets spread in sds Callout via `{...rest}`. With this change, if my component passes `icon={undefined}` (where undefined is determined programmatically), we still use the icon as dictated by sds style guidelines, rather than mui
- **Ticket:** [[sc-180631]](https://app.shortcut.com/genepi/story/180631)
=> feat(callout): allow consumer to conditionally override callout icon

src/core/InputDropdown/style.ts
Silences warning that Button produces:`Warning: Buttons without sdsStyle or sdsType props will be deprecated.` by allowing InputDropdown to forward prop `sdsStyle` to Button
My first contribution here I believe so I'm currently trying to read through the contribution guidelines and follow the steps there
Tested in CZ ID and verified that this indeed silenced the warning
Before:
https://user-images.githubusercontent.com/51972068/169142655-4c6f3eeb-f2fd-470b-9c67-af211d133807.mov
After:
https://user-images.githubusercontent.com/51972068/169142541-082793fb-8d72-49d1-9b70-ee5dbd74040f.mov
=> fix(input dropdown): forward sdsStyle to Button to silence Button warning

src/core/InputSearch/index.tsx
Removes Warning: React does not recognize the `data-testId` prop on a DOM element.
=> fix(inputsearch): remove extra data-test-id from index file

src/core/MenuItem/style.ts
**MenuItem**
removes extra min-height css property from menuItem component
=> style(MenuItem): removes extra min-height css property from menuItem component

src/core/DropdownMenu/index.stories.tsx, src/core/DropdownMenu/index.tsx, src/core/DropdownMenu/style.ts, src/core/MenuSelect/index.stories.tsx, src/core/MenuSelect/index.tsx, src/core/MenuSelect/style.ts
**MenuSelect, DropDownMenu**
Shortcut ticket: [sh-193551](https://app.shortcut.com/sci-design-system/story/193551/add-option-to-prevent-dropdown-from-clearing-search-bar-on-option-select)
"The search bar -- when search is true -- clears on selection of any item in the Dropdown. This isn't exactly a bug, but for the component we're working on in CZ GEN EPI we really need a way to change the behavior so that the search bar keeps its entered search term and the filtered options remain the same before and after selection of an item."
+ [Added] KeepSearchOnSelect option for menuSelect
+ [Added] KeepSearchOnSelect option for dropDownMenu
+ [Changed] Minor styling updates for MenuSelect component
If you set `keepSearchOnSelect` as `false`, after clicking on an option, the search box would be …
=> feat(menuselect, dropdownmenu): Add option to prevent Dropdown from clearing search bar on select

src/core/FilterTag/__snapshots__/index.test.tsx.snap, src/core/Tabs/index.stories.tsx, src/core/Tag/__snapshots__/index.test.tsx.snap, src/core/Tag/index.stories.tsx, src/core/Tag/style.ts
**Tag**
Using MUI's `darken()` function to replace the `::after` pseudo-element previously used to change the `:hover` and `:active` background-colors for custom colored tags.
=> refactor(tag): updates the hover and active logic for custom colored tags 

src/core/SegmentedControl/__snapshots__/index.test.tsx.snap, src/core/SegmentedControl/index.tsx, src/core/SegmentedControl/style.ts
Shortcut ticket: [[sh-XXXX](link)](https://app.shortcut.com/sci-design-system/story/199601/migrate-segmented-control)
migrate the segmented control component to use mui5
=> fix(segmented control): fixed styling after migration to v5

src/core/Dropdown/index.stories.tsx, src/core/Dropdown/index.tsx
- **What:** Add onClose to Dropdown
- **Why:** allow consumers to clear search or take other action
- **Discussion:** https://czi-sci.slack.com/archives/C032S43KKFV/p1656621162122669
http://localhost:6007/?path=/story/dropdown--search-with-on-close
=> feat(dropdown): allow consumers to pass onclose to dropdown

src/core/InputSearch/index.stories.tsx, src/core/InputText/index.stories.tsx
**InputText, InputSearch**
Adding a custom `name` attribute to MUI inputs prevents browser's default autocomplete menu
=> fix(inputtext): add name to inputs to prevent default autocomplete

src/core/Radio/__snapshots__/index.test.tsx.snap, src/core/Radio/index.stories.tsx, src/core/Radio/index.test.tsx, src/core/Radio/index.tsx
Shortcut ticket: [sh-XXXX](https://app.shortcut.com/sci-design-system/story/167634/update-stories-for-inputradio-to-csf-format)
The caption functionality is not yet implemented, I have made a ticket to implement it here: https://app.shortcut.com/sci-design-system/story/205655/add-caption-to-radio-button-component
As well, the label is not currently part of the library component, I have created a ticket to add the label to the component (consistent with checkbox) here: https://app.shortcut.com/sci-design-system/story/205654/add-optional-label-to-radio-button-component
In order to support testing and ZeroHeight, we are moving away from the StoriesOf() syntax and are adopting the [CSF …
=> refactor(radio button): change stories to csf format

src/core/MenuItem/__snapshots__/index.test.tsx.snap, src/core/MenuItem/index.stories.tsx, src/core/MenuItem/index.test.tsx
Shortcut ticket: [sh-167631](https://app.shortcut.com/sci-design-system/story/167631/update-stories-for-menuitem-to-csf-format)
This element does not have a live preview because its use is demonstrated in other dropdown live previews. 
In order to support testing and ZeroHeight, we are moving away from the StoriesOf() syntax and are adopting the [CSF Format](https://storybook.js.org/docs/react/api/csf).
In addition, there should be 3 stories per component: Default (all props are interactable via storybook controls, will occasionally include some external components to trigger effects and states), LivePreview (a number of components as defined by our ZeroHeight implementation), and Test (a single component).
New components will …
=> refactor(menuitem): change to default and test format

src/core/Tooltip/index.stories.tsx
**Tooltip**
Shortcut ticket: [sh167636](https://app.shortcut.com/sci-design-system/story/167636/update-stories-for-tooltip-to-csf-format)
update [live preview](https://www.figma.com/file/LS5AaNnOmjJ8ZDIuq0Tl9E/Zeroheight-Assets?node-id=21%3A60012)
=> refactor(tooltip): change stories to be csf

src/core/Icon/index.tsx, src/core/Icon/style.ts
- **What:** Pass custom classes through to icon svg component
- **Why:** so consuming applications can style icons directly with styled-components instead of using a wrapper
=> fix(icon): pass styled-components classnames to icon

src/core/ButtonIcon/index.stories.tsx, src/core/ButtonIcon/index.test.tsx
**ButtonIcon**
Shortcut ticket: [sh-167116](https://app.shortcut.com/sci-design-system/story/167116/add-medium-size-primary-and-secondary-iconbuttons-to-sds)
Add medium size Primary and Secondary IconButtons to SDS
=> refactor(buttonicon): update storybook arg types

src/common/styles-dictionary/css/variables.css, src/common/styles-dictionary/scss/_variables.scss, src/core/Link/index.stories.tsx, src/core/Link/index.tsx
I removed manual casting SDS Link as `RawLink`, since that's the root cause of the bug @ehoops-cz 's seeing in [slack](https://czi-sci.slack.com/archives/C032S43KKFV/p1660325285598779)
The intention was to fix a Link linter error in [this commit](https://github.com/chanzuckerberg/sci-components/commit/bfbb2f23cfc22b3b72e047df528cbe112848bdce), which I think casting the `styled(Link) as typeof Link` should have been enough? @masoudmanson please help confirm on Monday 🙏 Thanks so much!
=> fix(link): type

src/core/Tooltip/index.stories.tsx, src/core/Tooltip/index.tsx
**Tooltip**
Shortcut ticket: [sh-211324](https://app.shortcut.com/sci-design-system/story/211324/remove-subtitle-from-light-tooltip)
The light version should not have the ability to have a subtitle, only the main text.
=> refactor(tooltip): remove subtitle from light version

src/core/Button/index.stories.tsx
This ticket adds `onClick` in storybook!
=> docs(button): add onClick documentation in storybook

src/core/CellHeader/index.tsx, src/core/TableHeader/__snapshots__/index.test.tsx.snap, src/core/TableHeader/index.stories.tsx, src/core/TableHeader/index.test.tsx, src/core/TableHeader/index.tsx, src/core/TableHeader/style.ts
**TableHeader**
Shortcut ticket: [sh-213499](https://app.shortcut.com/sci-design-system/story/213499/tableheader-component)
Implemented with &lt;thead&gt; under the hood.
=> feat(tableheader): tableHeader implementation

src/core/CellComponent/__snapshots__/index.test.tsx.snap, src/core/CellComponent/style.ts
**CellComponent**
remove minimum width from cell component
=> fix(cellcomponent): remove min width

src/core/CellComponent/index.stories.tsx
**CellComponent**
Changed default story to allow demonstration of the vertical and horizontal alignment props. This was achieved by adding a toggle that switches between a cell with defined dimensions and a cell that fits the child's size
=> docs(cellcomponent): update cellcomponent default story to toggle between cell sizes

src/core/Checkbox/__snapshots__/index.test.tsx.snap, src/core/Checkbox/index.stories.tsx, src/core/Checkbox/index.test.tsx, src/core/Checkbox/index.tsx
**Checkbox**
Shortcut ticket: [[sh-XXXX](link)](https://app.shortcut.com/sci-design-system/story/205142/add-optional-label-to-checkbox-component)
Currently, the checkbox component only includes a checkbox square but is shown with a label in the Live Preview. We want to include the label as part of the component. Consumers have used it in its current state and built their own labels around it, so to ensure this isn't a breaking change the label will be optional.
=> feat(checkbox): added optional label to checkbox component

.github/workflows/storybook.yml
use a Personal Access Token in GitHub deploy workflow to enable triggering the deployment_status event and run the storybook_test workflow afterwards
=> feat(github): use a Personal Access Token in GitHub deploy workflow

src/core/Tabs/index.stories.tsx
**Tabs**
Shortcut ticket: [sh-210651](https://app.shortcut.com/sci-design-system/story/210651/reduce-width-of-tabs-live-previews-in-storybook)
Currently each Tabs component that is in the live preview story in Storybook is 250px wide; they should be 120px so they all fit on the screen in Zeroheight.
=> refactor(tabs): change width to 150px in live preview

src/core/ButtonIcon/style.ts, src/core/Dialog/__snapshots__/index.test.tsx.snap
A 'box-sizing' of 'content-box' resolved the primary ButtonIcon's size issue.
=> style(buttonicon): fix primary buttonIcon size

src/core/Tag/index.stories.tsx, src/core/Tag/style.ts
=> fix(tag): fix the type error for the hover prop of the tag component

src/core/Accordion/__snapshots__/index.test.tsx.snap, src/core/Banner/__snapshots__/banner.test.tsx.snap, src/core/Button/__snapshots__/index.test.tsx.snap, src/core/ButtonDropdown/__snapshots__/index.test.tsx.snap, src/core/ButtonIcon/__snapshots__/index.test.tsx.snap, src/core/CellBasic/__snapshots__/index.test.tsx.snap, src/core/CellHeader/__snapshots__/index.test.tsx.snap, src/core/ComplexFilter/__snapshots__/index.test.tsx.snap, src/core/Dialog/__snapshots__/index.test.tsx.snap, src/core/Dropdown/__snapshots__/index.test.tsx.snap, src/core/DropdownMenu/__snapshots__/index.test.tsx.snap, src/core/Icon/style.ts, src/core/InputDropdown/__snapshots__/index.test.tsx.snap, src/core/InputDropdown/index.stories.tsx, src/core/InputDropdown/index.tsx, src/core/InputDropdown/style.ts, src/core/LoadingIndicator/__snapshots__/index.test.tsx.snap, src/core/Notification/__snapshots__/notification.test.tsx.snap, src/core/Pagination/__snapshots__/index.test.tsx.snap, src/core/SegmentedControl/__snapshots__/index.test.tsx.snap, src/core/TableHeader/__snapshots__/index.test.tsx.snap
Ticket: #337 
Component Name: InputDropdown
Component Requirements: - New component variation, specific parameters as below
sdsType: single-select
sdsStyle: minimal
Details: on
Design link: https://www.figma.com/file/v8T3vabzkmbvH71sQ1EXzh/Kevin---Heatmap-Filters-Redesign?node-id=1047%3A35901&t=8JY2ukyrEk5NnJ6M-1
Team(s) Requesting: CZID
Component Needed By: This is part of the Heatmap - Move Filters to the left project. I will share the eng point of contact after handoff
Plan Details:
There is a version of this that exists but does not match the full requirements, we will take what exists in the code and updating it
=> feat(minimal inputdropdown): update Minimal Dropdown Style

.releaserc.js
This ticket changes the default release branch from `main` to `prod`. Which means future releases will require merging `main` into `prod`
Context:
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md#branches-properties
=> chore: Update default release branch from main to prod

src/core/MenuSelect/index.tsx
Requested by SCB to fix deprecated MenuSelect as well, since Dropdown and MenuSelect styles are different and SCB doesn't have time to restyle Dropdown to look closer to MenuSelect at the moment!
SCB ticket: https://github.com/chanzuckerberg/single-cell-data-portal/issues/4156
=> fix(MenuSelect): Fix backspace unselect item

src/core/Dropdown/index.stories.tsx, src/core/Dropdown/index.tsx, src/core/DropdownMenu/index.stories.tsx
**Dropdown**
GitHub issue: #414 
Amend the `Dropdown` menu to stay open only for the button variant.
=> refactor(dropdown): fix click outside behavior

packages/components/src/core/ComplexFilter/index.tsx
Changes ComplexFilter 'label' type from `string` to `ReactNode`. The Dropdown has label defined as ReactNode so I expected the ComplexFilter to also be a ReactNode -- https://github.com/chanzuckerberg/sci-components/blob/main/packages/components/src/core/Dropdown/index.tsx#L46
=> chore: Update ComplexFilter 'label' type from string to ReactNode

.storybook/main.js, .storybook/preview.js, package.json, packages/components/src/core/Button/index.stories.tsx, yarn.lock
**Updates for Chromatic tests**
Now the Button component has a single Live Preview story page that houses: 
- all the button styles (rounded, square, minimal) 
- × all the button types (primary, primary with icon, secondary, secondary with icon (except minimal style doesn't have this last one)
- × whether the button has an icon or not
- ×  whether the button is disabled or not (added May 3)
- × all their states (default, hover, active, focus-visible)
This will make it simpler for Chromatic testing: there will just need to be a single screenshot of this story page to compare every possible button permutation against in one go.
**Update (May 3):** 
I have updated the Button Live Preview to be more similar to the Tag's Live Preview (PR #445 ), which I worked on right after this Button story …
=> test: Update Button component Chromatic screenshots

packages/components/src/core/Button/index.stories.tsx
**Button**
Github issue: N/A
I updated the Live Preview story for Button so that the disabled iteration is in the same row, visually, as the pseudo-states. Disabled elements cannot be interacted with so cannot ever have any pseudo-state other than default, so it does not make sense to loop the `disabled = true` status through every pseudo-state iteration, only through the default state. Furthermore, the Storybook addon we use to simulate pseudo states does not properly render the states when `disabled=true` (it shows them as having hover, active, and focus statues visually which is not actually possible). So I removed every permutation of the Button for `disabled=true`, except for the case where pseudo-state is default. Then I put this instance in the same row in the UI as the other …
=> test(button): update Button Chromatic test's disabled iterations

packages/components/src/core/Notification/index.stories.tsx
Chromatic screenshot test for Notification component, which iterates through all permutations of its intent x extraContent x buttonOnClick props
re #497
**Notification**
Github issue: #497 
_Here's a screenshot of the UI:_
=> test(notification): notification screenshot test

packages/components/src/core/Banner/__snapshots__/banner.test.tsx.snap, packages/components/src/core/ButtonIcon/__snapshots__/index.test.tsx.snap, packages/components/src/core/ButtonIcon/style.ts, packages/components/src/core/CellHeader/__snapshots__/index.test.tsx.snap, packages/components/src/core/ComplexFilter/__snapshots__/index.test.tsx.snap, packages/components/src/core/Dialog/__snapshots__/index.test.tsx.snap, packages/components/src/core/Dropdown/__snapshots__/index.test.tsx.snap, packages/components/src/core/DropdownMenu/index.stories.tsx, packages/components/src/core/InputDropdown/InputDropdown.namespace-test.tsx, packages/components/src/core/InputDropdown/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/index.stories.tsx, packages/components/src/core/InputDropdown/index.tsx, packages/components/src/core/InputDropdown/style.ts, packages/components/src/core/Pagination/__snapshots__/index.test.tsx.snap, packages/components/src/core/Table/__snapshots__/index.test.tsx.snap, packages/components/src/core/TableHeader/__snapshots__/index.test.tsx.snap
**InputDropdown**
Github issue: #437
=> feat(inputdropdown): implement new redesigned inputdropdown

packages/components/src/core/NavigationJumpTo/NavigationJumpTo.namespace-test.tsx, packages/components/src/core/NavigationJumpTo/index.tsx, packages/components/src/core/NavigationJumpTo/style.ts
**NavigationJumpTo**
Github issue: #529 
For the new NavigationJumpTo component, is there a way to retrieve the current section? Or some onChange listener for when the user scrolls and the section changes?
We have a requirement to send an analytic event when a user scrolls into different sections using their mouse, and onChange didn’t seem to do anything when I tried it.
=> feat(navigationjumpto): emit the index of the navigation tab on scroll

packages/components/src/core/ComplexFilter/__snapshots__/index.test.tsx.snap, packages/components/src/core/Dropdown/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/index.stories.tsx, packages/components/src/core/InputDropdown/index.tsx, packages/components/src/core/InputDropdown/style.ts
**InputDropdown**
Github issue: #562
=> fix(inputdropdown): fix UserInput and Open state styles

packages/components/rollup.config.mjs, packages/components/src/core/Autocomplete/__snapshots__/index.test.tsx.snap, packages/components/src/core/Autocomplete/style.ts, packages/components/src/core/DropdownMenu/style.ts, packages/components/src/core/MenuSelect/index.stories.tsx, packages/components/src/core/MenuSelect/index.tsx, packages/components/src/core/SegmentedControl/__snapshots__/index.test.tsx.snap, packages/components/src/core/SegmentedControl/index.tsx, packages/components/src/core/SegmentedControl/style.ts, packages/data-viz/rollup.config.mjs
Fix breaking imports
Single Cell Team noticed that importing SDS Autocomplete throws the following error:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
And the root cause seems to be SDS TS -> JS transpiler didn't take ESM syntax into account when transpiled the code to CJS, so it resulted in importing the whole module instead of the intended module default export. 
For example,
```ts
// packages/components/dist/index.cjs.js
var Autocomplete = require('@mui/material/Autocomplete');
```
`Autocomplete` is the whole module object, when we just want `Autocomplete.default`
```
// we got the whole export module
Autocomplete {
autocompleteClasses: [Getter],
createFilterOptions: [Getter],
default: …
```
=> fix: Use named import for MUI components

packages/components/src/core/Autocomplete/__snapshots__/index.test.tsx.snap, packages/components/src/core/Autocomplete/index.stories.tsx, packages/components/src/core/Autocomplete/index.tsx, packages/components/src/core/Autocomplete/style.ts, packages/components/src/core/Dropdown/index.tsx, packages/components/src/core/DropdownMenu/index.stories.tsx, packages/components/src/core/DropdownMenu/index.tsx, packages/components/src/core/DropdownMenu/style.ts
**DropdownMenu**
Github issue: #563 
We need to refactor the DropdownMenu component to utilize the new Autocomplete component instead of the MUI's Autocomplete.
=> refactor(dropdownmenu): refactor DropdownMenu to use SDS Autocomplete

packages/components/src/core/Autocomplete/__snapshots__/index.test.tsx.snap, packages/components/src/core/Autocomplete/index.tsx, packages/components/src/core/Autocomplete/style.ts, packages/components/src/core/Dropdown/index.stories.tsx, packages/components/src/core/InputSearch/index.tsx, packages/components/src/core/InputSearch/style.ts
**InputSearch**
Github issue: #606 
When text is entered into the `InputSearch` component, you may have noticed the default HTML clear icon. However, this default icon doesn't align with our SDS iconography. To improve consistency and visual coherence, we need to replace the default clear icon with the SDS `xMark` icon.
**Current InputSearch:** 
<br/><br/>
**Desired Result:** 
<br/><br/>
**Live demo:**
https://616981d9028812003ade73f3-jouthyttmu.chromatic.com/?path=/story/inputs-inputsearch--default
=> style(inputsearch): change default html clear icon

packages/components/src/core/Autocomplete/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputSearch/style.ts, packages/components/src/core/InputText/index.stories.tsx, packages/components/src/core/InputText/style.ts
**InputSearch, InputText**
Github issue: #617 
This fixes the `intent` and `userInput` style bugs in the `InputSearch` and `InputText` components.
ZeroHeight Issue: https://czi.zeroheight.com/styleguide/s/66099/p/1596f8/c/107465
=> fix(inputsearch): fix intent and useInput styles

packages/components/src/core/Dropdown/index.tsx
1. Remove `onChange()` call in useEffect and use event handlers instead. This is to align with React best practices ([here](https://react.dev/learn/you-might-not-need-an-effect#how-to-remove-unnecessary-effects))
2. This resolves an infinite loop bug in Single Cell, since SC passes a new `onChange` function down to Dropdown every time a value changes
3. I have built the library and installed it locally to test it in SC and can confirm that the fix works 🎉 !
=> fix: call onChange in event callback instead of useEffect

packages/components/src/core/styles/common/defaultTheme.ts
**DefaultTheme**
Github issue: #686
Typo fixed in `defaultTheme` FontWeights object. Medium font-weight is equal to `500` now.
=> fix(defaulttheme): fix typo in fontWeights, medium = 500

packages/components/src/core/DropdownMenu/index.tsx
**DropdownMenu**
prefix the deprecation comment with a @deprecated tag so we get the strikethrough text to encourage users to migrate to the new type.
```javascript
/**
* @deprecated
* (masoudmanson): We've replaced DefaultDropdownMenuOption with DefaultAutocompleteOption
* as the preferred choice. However, for backward compatibility, we've exported this line to
* prevent potential TypeScript type issues for product teams using previous versions.
*/
export type DefaultDropdownMenuOption = DefaultAutocompleteOption;
```
=> docs(dropdownmenu): add @deprecated tag to comment

packages/components/src/core/Tabs/__snapshots__/index.test.tsx.snap, packages/components/src/core/Tabs/style.tsx
This PR adds a focus outline to the tabs component, for the [SDS accessibility hackday project](https://docs.google.com/spreadsheets/d/1NrbRZ4vTfeYtKU3GXrsmeS6QSHsNSwiV_ITLvo251WA/edit#gid=915097901).
[See it live on Chromatic](https://www.chromatic.com/component?appId=616981d9028812003ade73f3&csfId=tabs&buildNumber=1592&k=65677c0a9bbad7e409e35add-1200px-interactive-true&h=8&b=-1)
Keyboard usage of the tabs is actually working as expected:
- Tab onto and off of the active tab
- When focused on the active tab, left and right arrows changes the active tab
- Space changes to the selected tab
=> fix: add focused stylign to tabs

packages/components/src/core/LoadingIndicator/__snapshots__/index.test.tsx.snap, packages/components/src/core/LoadingIndicator/index.stories.tsx, packages/components/src/core/LoadingIndicator/index.tsx
Add live region to loading indicator, so screen readers will read out "Loading" Tested with VoiceOver on Safari.
Note that this won't tell people when loading is done. For that we'd need a system or components outside of the loading indicator.
But I think this is reasonable for now.
=> fix: add live region to loading indicator

packages/data-viz/src/core/HeatmapChart/index.tsx
=> refactor: Heatmap chart instance management

packages/components/src/core/Autocomplete/__storybook__/index.stories.tsx, packages/components/src/core/Autocomplete/__storybook__/stories/controlledOpen.tsx, packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/Autocomplete/components/AutocompleteBase/index.tsx, packages/components/src/core/Autocomplete/components/AutocompleteMultiColumn/index.tsx, packages/components/src/core/Autocomplete/index.tsx, packages/components/src/core/Dropdown/index.tsx, packages/components/src/core/DropdownMenu/index.tsx
**Autocomplete**
Github issue: #766 
This PR addresses issue #766 by fixing the controlled open state behavior of the Autocomplete component for both single and multi-column Autocompletes.
- Implemented a fix for the controlled open state behavior.
- Added handlers for both opening and closing the Autocomplete component.
- Demonstrated the usage of controlled open state with a simple example in the storybook (`Autocomplete/Controlled Open` Story)
A controlled open state for an Autocomplete that is opened by default can be demonstrated as follows:
```javascript
const [open, setOpen] = React.useState(true);
<Autocomplete
// Handles Autocomplete close
onClickAway={() => {
setOpen(false);
}}
// Handles Autocomplete Open
onClick={() => {
if (open) {
setOpen(false);
} else {
setOpen(true);
}
}} …
```
=> fix(autocomplete): fix controlled open state

packages/components/rollup.config.mjs
Github issue: #814 
Old PR: #825 
We need to add "use client"; in all SDS component files so that projects don’t have to do it manually, as shown here:
[Example PR Discussion](https://github.com/czbiohub-sf/CZBSF-Metadata-Tracker-refactor/pull/82#discussion_r1684929746).
Thanks to @tihuan (https://github.com/chanzuckerberg/sci-components/pull/825#pullrequestreview-2228530236), we now know that setting a banner in the Rollup config will automatically add the "use client"; directive to the top of output files.
Since we don’t use preserveModules: true in our Rollup configs, we don’t need to use the [rollup-plugin-preserve-directives](https://github.com/Ephem/rollup-plugin-preserve-directives), which would otherwise add the …
=> fix(rollup): add "use client;" banner on top of rollup outputs files

packages/components/src/core/ButtonIcon/style.ts
**Structural Element (Base, Gene, DNA, Chromosome or Cell)** Genes?
Github issue: N/A
When using an icon styled ButtonDropdown, there will be a console error message about prop `sdsStyle` being passed in the DOM.
`<ButtonDropdown />` renders `<ButtonIcon />` when `sdsStyle="icon"`. While `<ButtonIcon />` doesn't do more with the `sdsStyle` prop beyond that point, all the props (along with `sdsStyle`) are still being passed into the underlying components. There will still be a console error since `"sdsStyle"` wasn't included in the list of `doNotForwardProps`.
=> fix(ButtonIcon): add sdsStyle to doNotForwardProps

packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/ComplexFilter/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/Dropdown/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputCheckbox/__storybook__/index.stories.tsx, packages/components/src/core/InputCheckbox/styles.ts, packages/components/src/core/InputDropdown/__storybook__/index.stories.tsx, packages/components/src/core/InputDropdown/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/style.ts, packages/components/src/core/InputRadio/__storybook__/index.stories.tsx, packages/components/src/core/InputRadio/style.ts, packages/components/src/core/InputSearch/__storybook__/index.stories.tsx, packages/components/src/core/InputSearch/style.ts, packages/components/src/core/InputText/__storybook__/index.stories.tsx, packages/components/src/core/InputText/style.ts
**Inputs**
Github issue: #849 
The `InputText` component and rest of the input components currently supports `notice`, `negative`, and `default` intents. We need to add a `positive` intent to accommodate future form validation components.
=> feat(inputs): add positive intent to input compoennts

packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/Icon/__storybook__/stories/iconBank.tsx, packages/components/src/core/InputSearch/__storybook__/stories/default.tsx, packages/components/src/core/InputSearch/__storybook__/stories/test.tsx, packages/components/src/core/InputSearch/style.ts, packages/components/src/core/InputText/__storybook__/stories/default.tsx, packages/components/src/core/InputText/style.ts
**InputText, InputSearch**
Github issue: #853 
**Expected behavior**
We expect to be able to control the text input field's width similarly to how it's controlled in MUI.
=> fix(inputtext): remove min-width from InputText and InputSearch

packages/components/src/core/SegmentedControl/__storybook__/index.stories.tsx, packages/components/src/core/SegmentedControl/__storybook__/stories/controlledSegmentedControl.tsx, packages/components/src/core/SegmentedControl/__storybook__/stories/default.tsx, packages/components/src/core/SegmentedControl/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/SegmentedControl/index.tsx, packages/components/src/core/SegmentedControl/style.ts
**SegmentedControl**
Github issue: #868 
- Component Refactored
- New Storybook Stories Added to Cover the Changes
- `disabled` Prop Added to the `buttonDefinition`
- Controlled/Uncontrolled State Added to the Component
=> feat(SegmentedControl): add disabled state in button definition

packages/components/src/core/Link/__storybook__/index.stories.tsx, packages/components/src/core/Link/__storybook__/stories/longText.tsx, packages/components/src/core/Link/style.ts
=> fix(link): fix multi-line link text-decorations

packages/components/rollup.config.mjs, packages/data-viz/rollup.config.mjs
Adding `auto` to `interop` config so that it can automatically manage the compatibility for imports/exports between CommonJS and ES modules. (ref: https://rollupjs.org/configuration-options/#output-interop)
Our unit tests (via Vitest) with SDS components were failing with the following error:
```
Error: TypeError: styled is not a function
❯ Object.<anonymous> node_modules/@czi-sds/components/dist/index.cjs.js:1309:30
```
This happened after we upgraded SDS from `20.5.0` to `21.6.1`. We suspect something on the output has changed because of the [SDS migration from babel SWC](https://github.com/chanzuckerberg/sci-components/pull/841).
- I copied the new CJS output file and replace the existing one in our codebase's node_modules. Ran our unit tests, the error no longer appears and the tests …
=> build: set interop to auto for output config

packages/components/src/core/SegmentedControl/index.tsx
**SegmentedControl**
Github issue: #890 
Changed the `SegmentedControl` component to allow all buttons to be deselected. Before, it always required one button to stay active, but now that restriction is gone. I updated the `handleActive` function to remove the condition that forced a selection.
=> fix(segmentedcontrol): allow all buttons to be deselected

packages/components/src/common/warnings.ts, packages/components/src/core/Tooltip/__storybook__/constants.ts, packages/components/src/core/Tooltip/__storybook__/index.stories.tsx, packages/components/src/core/Tooltip/index.tsx, packages/components/src/core/Tooltip/style.ts
**Tooltip**
Github issue: #896 
Connor and I chatted about this and decided to go with a boolean prop called invertStyle with the dark background being the default value (which is "false")
invertStyle: false = dark background Tooltip
invertStyle: true = light background Tooltip
We'll use the same prop on the NavFooter and NavHeader components.
=> refactor(tooltip): rename sdsStyle prop to invertStyle

packages/components/src/common/styles-dictionary/custom-formatters/tailwindFormatter.mjs, packages/components/src/common/styles-dictionary/json/tailwind.json
**Tailwind**
Github issue: #913 
The current design token definitions exported for Tailwind using Style Dictionary are incorrect. We need to ensure that the generated tailwind.json file adheres to the correct format and aligns with Tailwind’s configuration standards.
The new typography variables are defined in the sds tailwind.json file like so:
```json
{
"typography": {
"sds-body-xxxs-400-narrow": {
"css": {
"fontFamily": "Inter, sans-serif",
"fontSize": "12px",
"fontStyle": "normal",
"fontVariantNumeric": "normal",
"fontWeight": "400",
"letterSpacing": "0.1px",
"lineHeight": "18px",
"textTransform": "none"
}
}, 
...
}
}
```
To include these typography variables in your Tailwind setup, you can import them from the sds `tailwind.json` file and feed them into the extend section of your …
=> fix(tailwind): new typography config for tailwind

packages/components/src/core/ContentCard/ContentCard.types.ts, packages/components/src/core/ContentCard/__tests__/index.test.tsx, packages/components/src/core/ContentCard/components/ContentCardTitle/index.tsx, packages/components/src/core/ContentCard/index.tsx
**ContentCard**
Github issue: https://czi.atlassian.net/jira/software/c/projects/SCIDS/list?selectedIssue=SCIDS-993
=> feat(ContentCard): Add ReactNode Support to ContentCard Title Components

packages/components/src/core/TooltipTable/__storybook__/index.stories.tsx, packages/components/src/core/TooltipTable/index.tsx, packages/components/src/core/TooltipTable/style.ts
**TooltipTable**
Jira issue: https://czi.atlassian.net/browse/SCIDS-1118
Added a new showSectionHeader prop to control showing/hiding the section headers.
=> fix: Add showSectionHeader prop to TooltipTable

packages/components/src/core/Autocomplete/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/MenuItem/style.ts
**MenuItem**
Jira Ticket: https://czi.atlassian.net/browse/SCIDS-1122?atlOrigin=eyJpIjoiMmQ0M2FjNjdjMzY4NGI2YzgzZjUyZDlmZmFlNDhlZWIiLCJwIjoiaiJ9
<div style="display: flex; align-items: center; justify-content: center">
===>
</div>
=> fix(MenuItem): Add display flex to icon wrapper to fix the icon position

packages/components/src/core/Panel/style.ts
**Panel**
Github issue: https://czi.atlassian.net/browse/SCIDS-1127?atlOrigin=eyJpIjoiMTUzNjMwNzZiZDQ4NGVkNGJjNDk5MTU5NTRmMTYyZTgiLCJwIjoiaiJ9
=> fix: Update panel header margin-bottom to use spaces.xl instead of spaces.xxl

packages/components/src/core/Dropdown/__storybook__/index.stories.tsx, packages/components/src/core/Dropdown/index.tsx, packages/components/src/core/DropdownMenu/index.tsx, packages/components/src/core/DropdownMenu/style.ts
Request from [Slack](https://czi-sci.slack.com/archives/C032S43KKFV/p1748541194214919)
Need to add an optional prop `isSearchAutoFocus` on `Dropdown` and `DropdownMenu` to allow disabling DropdownMenu's InputBase `autoFocus` value
`<Dropdown isSearchAutoFocus={false} ... />`
https://github.com/user-attachments/assets/87ac12aa-04f0-42b0-a7ed-327a122f4528
=> feat(Dropdown): Add optional prop - isSearchAutoFocus

packages/components/src/core/ComplexFilter/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/Dropdown/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/__storybook__/index.stories.tsx, packages/components/src/core/InputDropdown/__tests__/__snapshots__/index.test.tsx.snap, packages/components/src/core/InputDropdown/index.tsx, packages/components/src/core/InputDropdown/style.ts
**InputDropdown**
Slack issue: https://czi-sci.slack.com/archives/C032S43KKFV/p1759560447385269
we're seeing a small bug in the label for the Dropdown component in sds. If I create a new sds app using:
```
$ npx create-next-app --example https://github.com/chanzuckerberg/create-sds-app tmp
$ cd tmp && yarn
```
and then make the following change (wrap the label in an element:
```
diff --git a/app/page.tsx b/app/page.tsx
index 2229e24..48eaf54 100644
--- a/app/page.tsx
+++ b/app/page.tsx
@@ -70,7 +70,7 @@ export default function Home() {
<CodeExampleWrapper>
<p>Example SDS Dropdown:</p>
<Dropdown
-          label="Select Size"
+          label=<span>Select Size</span>
options={sizeOptions}
value={selectedSize}
multiple={false}
```
We see the `[object Object]` in the dropdown rather than the …
=> fix(inputdropdown): fix label
