- .eslintrc.js
- package.json
- src/core/Autocomplete/index.tsx
- src/core/MenuItem/index.stories.tsx
- src/core/MenuItem/index.tsx
- src/core/MenuItem/style.ts
- src/core/styles/common/constants/black.ts
- src/core/styles/common/constants/boxShadows.ts
- src/core/styles/common/constants/fontWeights.ts
- src/core/styles/common/constants/gray.ts
- src/core/styles/common/constants/spaces.ts
- src/core/styles/common/constants/white.ts
- src/core/styles/common/mixins/body.ts
- src/index.ts
- yarn.lock
> Thuang dropdown item multi select columns

- .eslintrc.js
- .storybook/main.js
- .storybook/preview.js
- package.json
- rollup.config.js
- src/common/storybookConstants.ts
- src/core/Alert/index.stories.tsx
- src/core/Alert/index.tsx
- src/core/Button/index.tsx
- src/core/Checkbox/index.tsx
- src/core/Menu/index.stories.tsx
- src/core/Menu/index.tsx
- src/core/MenuItem/index.stories.tsx
- src/core/MenuItem/index.tsx
- src/core/MenuItem/style.ts
- src/core/Tabs/index.stories.tsx
- src/core/Tabs/index.tsx
- src/core/styles/common/defaultTheme.ts
- src/core/styles/common/mixins/body.ts
- src/core/styles/common/selectors/theme.ts
- src/core/styles/index.ts
- src/index.ts
- tsconfig.json
- yarn.lock
1. Add Dropdown component
2. Add selectors for getting values from theme
3. Fix Story and Emotion not playing well together [issue](https://github.com/storybookjs/storybook/issues/10231#issuecomment-728038867)
4. Update Storybook to inject theme for Emotion
5. Update `package.json` to publish the library to `npm`, using placeholder name `czifui`
6. Update `rollup` config to spit out TS definition files correctly
7. Add new `MenuItem` stories
8. Update `defaultTheme.ts` to match IDseq design system
9. Update mixin to use `theme` values
10. Reorganize exports in `src/index.ts`
> Productionize component library

- package.json
- src/core/List/index.stories.tsx
- src/core/List/index.tsx
- src/core/List/style.ts
- src/core/ListItem/index.tsx
- src/core/ListItem/style.ts
- src/core/styles/common/selectors/theme.ts
Add ordered List and nested list option!
> Thuang add list and link

- README.md
- package.json
- src/core/Alert/index.stories.tsx
- src/core/Alert/index.tsx
- src/core/Alert/style.ts
- src/core/TooltipTableContent/index.tsx
- src/core/styles/common/defaultTheme.ts
- src/index.ts
Just realized that I forgot to push a PR for updating the code to allow customizing themes 🤦 
And this PR also adds Alert export and refactored it a little to follow other components' patterns 😄 
PTAL thank you!!
> thuang-update-alert

- LICENSE
- README.md
- docs/contribution.md
Readme updates for making this repository public.  Following the czi guidelines here: https://czi.atlassian.net/wiki/spaces/TECH/pages/1900972990/Creating+an+Open+Source+Project+at+CZI#CreatinganOpenSourceProjectatCZI-Licensing
> Readme updates for open sourcing

- .github/workflows/push-tests.yml
Adding a build test step to ensure every PR builds 🚀 !
Testing if build test works by intentionally failing!
Updated: Failed as expected 🙆‍♂️
> thuang-add-build-test

- src/core/styles/common/defaultTheme.ts
- src/core/styles/common/selectors/theme.ts
[ticket link](https://app.clubhouse.io/sci-design-system/story/157920/add-border-styles-to-library)
Add border styles to library. 
First PR in the repo, so please let me know if this needs fixes
> [ch157920] Add border styles to library

- .eslintrc.js
- README.md
- package.json
- src/core/Alert/style.ts
- src/core/styles/common/defaultTheme.ts
This PR fixes Alert component using the component library's default theme instead of the product's default theme 😆 
PTAL thank you!!
> Thuang fix alert

- package.json
- src/core/styles/common/defaultTheme.ts
For backward compatibility 🔥 Thank you!
> thuang-fix-createTheme

- .storybook/webpack.config.js
- package.json
- src/common/utils.ts
- src/core/ComplexFilter/components/Chips/index.tsx
- src/core/ComplexFilter/components/Chips/style.ts
- src/core/ComplexFilter/index.stories.tsx
- src/core/ComplexFilter/index.tsx
- src/core/ComplexFilter/style.ts
- src/core/InputDropdown/index.tsx
- src/core/InputDropdown/styles.ts
- src/core/MenuItem/index.tsx
- src/core/MenuItem/style.ts
- src/core/MenuSelect/index.stories.tsx
- src/core/MenuSelect/index.tsx
- src/core/MenuSelect/style.ts
- src/core/Tooltip/index.tsx
- src/index.ts
- yarn.lock
[Ticket](https://app.clubhouse.io/sci-design-system/story/152399/complex-filter-integration)
This PR integrates all the complex filter subcomponents together 🎉 
It supports:
1. Single Select
2. Multiple Select
3. Search
4. Both controlled and uncontrolled selected values
More comments will be added inline 🙆‍♂️ Thank you!
> thuang-complex-filter-integration-152399

- .github/workflows/storybook.yml
- package.json
Now we'll auto deploy storybook whenever `main` gets a new commit 👌 🚀 !
> chore: add auto storybook deploy

- src/common/styles-dictionary/css/variables.css
- src/common/styles-dictionary/scss/_variables.scss
- src/common/styles-dictionary/style-dictionary.json
remove comma from font shorthand
> fix(styles-dictionary): fix font shorthand variable

- .husky/pre-commit
- jest.config.js
- src/core/Callout/components/CalloutTitle/style.ts
- src/core/Tabs/__snapshots__/index.test.tsx.snap
- src/core/Tabs/index.stories.tsx
- src/core/Tabs/index.test.tsx
- src/core/Tabs/index.tsx
Tickets:
https://app.shortcut.com/sci-design-system/story/152077/update-tabs-component-for-sds
https://app.shortcut.com/sci-design-system/story/167635/update-stories-for-tabs-to-csf-format
1. Updates Tabs to match style specs
2. Update story book stories to follow CSF format
3. Add simple tests
PTAL thank you 😄 🙏
> fix(tabs): update Tabs to match style specs

- .github/workflows/storybook.yml
---
title: "type_of_change(scope_of_work): ticket title"
reviewers: "sds-eng, sds-design"
---
Storybook deployment:
Somehow it failed: https://github.com/chanzuckerberg/sci-components/runs/4973310373?check_suite_focus=true
My guess is that because I was using `npm` instead of `yarn`, and I removed `package-lock.json`, since we use `yarn.lock`. So the fix I think is just updating the command to run `yarn install` and `yarn build-storybook` 🤞 
Thank you!
> ci(hosted storybook): hosted storybook deploy GH action

- src/core/Button/index.tsx
> fix(button): buttonProps add C default value

- README.md
> docs(readme): update README to add Zeroheight reference

- src/core/Button/style.ts
> feat(button): Keyboard only focus outline

- src/core/Dropdown/index.tsx
- src/core/MenuSelect/index.tsx
> fix(menuselect and dropdown): tiny bug fixes

- src/core/InputSearch/index.tsx
- src/core/InputText/index.stories.tsx
- src/core/Tooltip/index.stories.tsx
> fix(inputsearch): fix ref type

- src/core/Button/index.stories.tsx
- src/core/Button/style.ts
- src/core/Icon/style.ts
- **What:** Update styles on minimal button
- **Ticket:** [[sc-154441]](https://app.shortcut.com/genepi/story/154441)
> fix(button): update styles for minimal button

- src/core/Button/index.tsx
- src/core/Button/style.ts
- src/core/Dialog/__snapshots__/index.test.tsx.snap
- src/core/InputDropdown/__snapshots__/index.test.tsx.snap
- src/core/InputSearch/__snapshots__/index.test.tsx.snap
- src/core/InputText/__snapshots__/index.test.tsx.snap
- src/core/Notification/__snapshots__/notification.test.tsx.snap
- src/core/Tabs/__snapshots__/index.test.tsx.snap
- src/core/Tabs/components/LabelWithCount/style.ts
- src/core/Tabs/style.tsx
- src/core/Tooltip/__snapshots__/tooltip.test.tsx.snap
- src/core/TooltipTable/__snapshots__/tooltipTable.test.tsx.snap
1. Update snapshots
2. Fix Tabs bug that pass `sdsSize` to DOM
3. Fix MinimalSecondaryButton by using code from [Button PR](https://github.com/chanzuckerberg/sci-components/pull/157/files) - since this was causing Notification test to fail
> test: fix tests

- src/core/Banner/__snapshots__/banner.test.tsx.snap
- src/core/Banner/banner.test.tsx
- src/core/Banner/index.stories.tsx
- src/core/Banner/index.tsx
- src/core/Banner/style.ts
- **What:** Create SDS banner
- **Ticket:** [[sc-190031]](https://app.shortcut.com/sci-design-system/story/190031)
- **Design:** https://www.figma.com/file/EaRifXLFs54XTjO1Mlszkg/Science-Design-System-Reference?node-id=8859%3A104122
> feat(banner): add banner

- src/core/InputSlider/__snapshots__/index.test.tsx.snap
- src/core/InputSlider/index.stories.tsx
- src/core/InputSlider/index.test.tsx
- src/core/InputSlider/index.tsx
- src/core/InputSlider/style.ts
- src/index.ts
**InputSlider**
Shortcut ticket: [sh-157945](https://app.shortcut.com/sci-design-system/story/157945/implement-inputslider)
Acceptance Criteria
add slider input component to code repo and story book
input uses MUI slider component
component name: InputSlider
> feat(inputslider): inputSlider Implementation

- src/core/Alert/index.stories.tsx
**Alert**
Fix error for snackbar alert on MUI v5
> fix(alert): fix snackbar alert error on v5

- .storybook/main.js
- README.md
- docs/eng-how-to.md
- package.json
- rollup.config.js
- src/core/Accordion/__snapshots__/index.test.tsx.snap
- src/core/Accordion/components/AccordionDetails/index.tsx
- src/core/Accordion/components/AccordionDetails/style.ts
- src/core/Accordion/components/AccordionHeader/index.tsx
- src/core/Accordion/components/AccordionHeader/style.ts
- src/core/Accordion/index.tsx
- src/core/Accordion/style.ts
- src/core/Banner/index.stories.tsx
- src/core/Banner/style.ts
- src/core/Checkbox/index.stories.tsx
- src/core/InputSlider/__snapshots__/index.test.tsx.snap
- src/core/Radio/index.stories.tsx
- src/core/Tag/index.stories.tsx
- src/core/Tag/style.ts
- src/core/TagFilter/index.stories.tsx
- src/core/TagFilter/index.tsx
- src/core/TagFilter/style.ts
- src/core/TooltipTable/__snapshots__/tooltipTable.test.tsx.snap
- src/core/TooltipTable/style.ts
- yarn.lock
**Bet branch**
Shortcut ticket: [sh-204313](https://app.shortcut.com/sci-design-system/story/204313/final-clean-up-of-codebase)
> refactor(beta): remove all v4 dependencies and update readme file

- src/core/Dropdown/index.stories.tsx
A bit of code cleanup that I forgot to do in #223
> refactor(dropdown): clean up unneeded code in storybook demo

- src/core/Tooltip/style.ts
**Tooltip**
Adjust the styles for the Tooltip arrow
> style(tooltip): arrow style adjustment

- src/core/Tabs/index.stories.tsx
**Tabs (Base, Gene, DNA, Chromosome or Cell)**
The last branch/merge was off of beta, then beta was merged into main. The last branch had a lot of merge conflicts so I made a new branch off of main.
> refactor(tabs): updated live preview

- src/core/ComplexFilter/__snapshots__/index.test.tsx.snap
- src/core/ComplexFilter/index.stories.tsx
- src/core/ComplexFilter/index.test.tsx
- src/core/ComplexFilter/style.ts
**ComplexFilter**
Shortcut ticket: [sh-167625](https://app.shortcut.com/sci-design-system/story/167625/update-stories-for-complexfilter-to-csf-format)
Update stories for ComplexFilter to CSF format
> refactor(complexfilter): change stories to CSF format

- src/core/Dropdown/index.tsx
Add `DropdownPaper` export to the `Dropdown` component.
> feat(dropdown): restore DropdownPaper export to the Dropdown component

- src/core/BasicCell/__snapshots__/index.test.tsx.snap
- src/core/BasicCell/index.stories.tsx
- src/core/BasicCell/index.test.tsx
- src/core/BasicCell/index.tsx
- src/core/BasicCell/style.ts
- src/index.ts
**BasicCell**
Shortcut ticket: [sh-208409](https://app.shortcut.com/sci-design-system/story/208409/basiccell-component)
Implemented with &lt;td&gt; under the hood.
> feat(basiccell): BasicCell Component Implementation

- src/core/Table/index.stories.tsx
> fix(table): correct the spelling mistake in the table component

- src/core/Dropdown/__snapshots__/index.test.tsx.snap
- src/core/Dropdown/index.tsx
**Dropdwon**
Shortcut ticket: [sh-216338](https://app.shortcut.com/sci-design-system/story/216338/fix-the-opening-and-closing-functionality-of-the-dropdown-component)
> fix(dropdown): fix dropdown closing bug

- src/common/svgs/IconChevronLeftLarge.svg
- src/common/svgs/IconChevronLeftSmall.svg
- src/core/Icon/map.ts
- src/core/Pagination/__snapshots__/index.test.tsx.snap
- src/core/Pagination/components/PageListDropdown/index.tsx
- src/core/Pagination/components/PageListDropdown/style.ts
- src/core/Pagination/index.stories.tsx
- src/core/Pagination/index.test.tsx
- src/core/Pagination/index.tsx
- src/core/Pagination/style.ts
- src/core/Pagination/usePagination.ts
- src/index.ts
Shortcut ticket: [sh-208412](https://app.shortcut.com/sci-design-system/story/208412/pagination-component)
> feat(pagination): Masoudamjadi/sc 208412/pagination component

- src/core/ComplexFilter/index.tsx
- src/core/DropdownMenu/style.ts
**DropdownMenu**
Remove `onClickAway` from forwardedProps
> fix(dropdownmenu): remove onClickAway from forwardedProps

- src/core/ButtonIcon/style.ts
Remove `SdsIconProps` from forwardedProps in ButtonIcon component.
> fix(buttonicon): remove sdsIconProps from forwardedProps

- src/common/warnings.ts
- src/core/Tooltip/index.tsx
https://czi-sci.slack.com/archives/C032S43KKFV/p1673986801792699
> refactor(tooltip): use showWarningIfFirstOccurence in tooltip component

- src/core/TooltipTable/index.tsx
**TooltipTable**
Shortcut ticket: #356
> fix(tooltiptable): fix non-unique react keys

- package.json
Update `react` peer dependency to allow react 18
> feat(package.json): support React 18 peer dependency

- .github/PULL_REQUEST_TEMPLATE.md
Update the pull request template file and replace the shortcut links with GitHub project.
> feat(github): update pull request template

- .eslintrc.js
- packages/components/src/core/Tag/index.stories.tsx
- packages/components/src/core/Tag/index.testUtils.tsx
> refactor: tag screenshot feedback

- .github/ISSUE_TEMPLATE/feature_request
> feat(github): Create feature_request

- package.json
- packages/components/src/core/InputCheckbox/__snapshots__/index.test.tsx.snap
- packages/components/src/core/InputCheckbox/index.stories.tsx
- packages/components/src/core/InputCheckbox/index.tsx
**InputCheckbox**
Github issue: #599 
I improved the InputCheckbox component by cleaning up the code, removing unnecessary parts, and making it neater. I also did the same for the Storybook file, making sure the documentation and how the component works in Storybook are better. These changes make the code easier to maintain and understand.
> refactor(inputcheckbox): refactor the code and clean up

- packages/components/src/core/styles/common/SDSAppTheme.ts
- packages/components/src/core/styles/common/defaultTheme.ts
- packages/components/src/core/styles/common/types.ts
**SDS Theme**
Github issue: #769 
Fix backward compatibility issues with SDS Default App Theme.
> fix(sdstheme): fix SDS Theme backward compatibility

- packages/components/src/core/ComplexFilter/index.tsx
- packages/components/src/core/Dropdown/__storybook__/stories/test.tsx
- packages/components/src/core/Dropdown/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/Dropdown/index.tsx
Props are now accurately propagated to the underlying button component.
> fix(dropdown): fix props propagating

- packages/components/src/core/ComplexFilter/index.tsx
**ComplexFilter**
Github issue: #823
> fix(complexfilter): fix re-rendering bug

- packages/components/CHANGELOG.md
> chore(changelog): update changelog

- packages/components/src/common/styles-dictionary/css/variables.css
- packages/components/src/core/Button/index.tsx
- packages/components/src/core/ContentCard/ContentCard.types.ts
- packages/components/src/core/ContentCard/__storybook__/index.stories.tsx
- packages/components/src/core/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/ContentCard/components/ContentCardActions/index.tsx
- packages/components/src/core/ContentCard/components/ContentCardImageMedia/index.tsx
- packages/components/src/core/ContentCard/components/ContentCardTitle/index.tsx
- packages/components/src/core/ContentCard/index.tsx
- packages/components/src/core/ContentCard/style.ts
- packages/components/src/core/NavigationHeader/__storybook__/index.stories.tsx
- packages/components/src/core/NavigationHeader/__storybook__/stories/default.tsx
- packages/components/src/core/NavigationHeader/__tests__/NavigationHeader.namespace-test.tsx
- packages/components/src/core/NavigationHeader/__tests__/index.test.tsx
- packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/index.tsx
- packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/style.ts
- packages/components/src/core/NavigationHeader/index.tsx
- packages/components/src/core/NavigationHeader/style.ts
> refactor(navigationheader): vcp changes

- packages/components/src/core/Button/index.tsx
- packages/components/src/core/ContentCard/ContentCard.types.ts
- packages/components/src/core/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/ContentCard/index.tsx
- packages/components/src/core/ContentCard/style.ts
**Content Card**
Jira issue: [SCIDS-984](https://czi.atlassian.net/browse/SCIDS-984)
[SCIDS-984]: https://czi.atlassian.net/browse/SCIDS-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ContentCard): Fixed ContentCard content height + Fixed TS types on CC

- packages/components/src/core/NavigationHeader/__storybook__/index.stories.tsx
- packages/components/src/core/NavigationHeader/__tests__/NavigationHeader.namespace-test.tsx
- packages/components/src/core/NavigationHeader/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/index.tsx
- packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/style.ts
- packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/index.tsx
- packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/style.ts
- packages/components/src/core/NavigationHeader/style.ts
**NavigationHeader**
Jira issue: https://czi.atlassian.net/jira/software/c/projects/SCIDS/list?selectedIssue=SCIDS-990
> feat(NavigationHeader): Added dropdown variant to primary nav items

- packages/components/src/core/NavigationJumpTo/__storybook__/index.stories.tsx
- packages/components/src/core/NavigationJumpTo/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/NavigationJumpTo/index.tsx
- packages/components/src/core/NavigationJumpTo/style.ts
- packages/components/src/core/NavigationJumpTo/useIntersection.ts
**NavigationJumpTo**
Github issue: https://czi.atlassian.net/browse/SCIDS-1120?atlOrigin=eyJpIjoiZjYzN2IwMzA0OWQwNDFiZDhkZTg4YzgyZDExYjNlYzIiLCJwIjoiaiJ9
> fix(NavigationJumpTo): Fixed NavigationJumpTo Scroll and whiteSpace styles

- packages/components/src/core/Tooltip/__storybook__/constants.tsx
- packages/components/src/core/Tooltip/__storybook__/index.stories.tsx
- packages/components/src/core/Tooltip/__storybook__/stories/default.tsx
- packages/components/src/core/Tooltip/index.tsx
- packages/components/src/core/Tooltip/style.ts
**Tooltip**
Jira issue: https://czi.atlassian.net/browse/SCIDS-1128?atlOrigin=eyJpIjoiZjM5NTU5OTY0ZTU0NGMyYWE2ODllYWQyNzQyOGMxNjUiLCJwIjoiaiJ9
- New `componentSlot` prop on `Tooltip` componenet
- New `textAlign` prop 
- Fixed `width` prop on Tooltips
> feat: Added new component slot prop to tooltips and fixed width prop

- packages/components/src/core/NavigationHeader/__storybook__/constants.tsx
- packages/components/src/core/NavigationHeader/__storybook__/index.stories.tsx
- packages/components/src/core/NavigationHeader/__tests__/__snapshots__/index.test.tsx.snap
- packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/index.tsx
- packages/components/src/core/NavigationHeader/components/NavigationHeaderPrimaryNav/style.ts
- packages/components/src/core/NavigationHeader/components/NavigationHeaderSecondaryNav/index.tsx
- packages/components/src/core/NavigationHeader/components/style.ts
- packages/components/src/core/NavigationHeader/utils.ts
> feat: add sections to dropdown menus in navs

- .github/workflows/release.yml
Forgot to add them to release script
> chore: add zeroheight envs to release script

- scripts/evaluate-code/README.md
- scripts/evaluate-code/index.cjs
- scripts/evaluate-code/plugins.cjs
- scripts/evaluate-code/reporters.cjs
> chore: Eval README update
